apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-preview-apps
  
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: amikh
        repo: gitops-cert-level-3-examples
        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'myapp-{{.branch}}-{{.number}}'
    spec:
      source:
        repoURL: 'https://github.com/amikh/gitops-cert-level-3-examples.git'
        targetRevision: '{{.head_sha}}'
        path: preview-environments/kustomize-preview-app/
        kustomize:
          images:
            - 'docker.io/kostiscodefresh/my-preview-app:{{.branch_slug}}'
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-{{.branch_slug}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true